In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
import keras
from keras import layers
import tensorflow as tf
from keras.regularizers import l1

In [ ]:
data = pd.read_csv('TCGA_InfoWithGrade.csv')

In [ ]:
data.head()

Grade  Gender  Age_at_diagnosis  Race  IDH1  TP53  ATRX  PTEN  EGFR  CIC  \
0      0       0             51.30     0     1     0     0     0     0    0   
1      0       0             38.72     0     1     0     0     0     0    1   
2      0       0             35.17     0     1     1     1     0     0    0   
3      0       1             32.78     0     1     1     1     0     0    0   
4      0       0             31.51     0     1     1     1     0     0    0   

   ...  FUBP1  RB1  NOTCH1  BCOR  CSMD3  SMARCA4  GRIN2A  IDH2  FAT4  PDGFRA  
0  ...      1    0       0     0      0        0       0     0     0       0  
1  ...      0    0       0     0      0        0       0     0     0       0  
2  ...      0    0       0     0      0        0       0     0     0       0  
3  ...      0    0       0     0      0        0       0     0     1       0  
4  ...      0    0       0     0      0        0       0     0     0       0  

[5 rows x 24 columns]

In [ ]:
data.columns

Index(['Grade', 'Gender', 'Age_at_diagnosis', 'Race', 'IDH1', 'TP53', 'ATRX',
       'PTEN', 'EGFR', 'CIC', 'MUC16', 'PIK3CA', 'NF1', 'PIK3R1', 'FUBP1',
       'RB1', 'NOTCH1', 'BCOR', 'CSMD3', 'SMARCA4', 'GRIN2A', 'IDH2', 'FAT4',
       'PDGFRA'],
      dtype='object')

In [ ]:
IDH1 = data.loc[:, "IDH1"]
TP53 = data.loc[:, "TP53"]

ATRX = data.loc[:, "ATRX"]
PTEN = data.loc[:, "PTEN"]

EGFR = data.loc[:, "EGFR"]
CIC = data.loc[:, "CIC"]

MUC16 = data.loc[:, "MUC16"]
PIK3CA = data.loc[:, "PIK3CA"]

NF1 = data.loc[:, "NF1"]
PIK3R1 = data.loc[:, "PIK3R1"]

FUBP1 = data.loc[:, "FUBP1"]
RB1 = data.loc[:, "RB1"]

NOTCH1 = data.loc[:, "NOTCH1"]
BCOR = data.loc[:, "BCOR"]

CSMD3 = data.loc[:, "CSMD3"]
SMARCA4 = data.loc[:, "SMARCA4"]

GRIN2A = data.loc[:, "GRIN2A"]
IDH2 = data.loc[:, "IDH2"]

FAT4 = data.loc[:, "FAT4"]
PDGFRA = data.loc[:, "PDGFRA"]

grade = data.loc[:, "Grade"]


In [ ]:
gene_mutation = [grade.value_counts(), IDH1.value_counts(), TP53.value_counts(), ATRX.value_counts(), PTEN.value_counts(),
                 EGFR.value_counts(), CIC.value_counts(), MUC16.value_counts(),
                 PIK3CA.value_counts(), NF1.value_counts(), PIK3R1.value_counts(),
                 FUBP1.value_counts(), RB1.value_counts(), NOTCH1.value_counts(),
                 BCOR.value_counts(), CSMD3.value_counts(), SMARCA4.value_counts(),
                 GRIN2A.value_counts(), IDH2.value_counts(), FAT4.value_counts(),
                 PDGFRA.value_counts()]

def print_gene_mutation():
  for i in range(0, len(gene_mutation)):
    print(gene_mutation[i])
    i += 1

In [ ]:
print_gene_mutation()

0    487
1    352
Name: Grade, dtype: int64
0    435
1    404
Name: IDH1, dtype: int64
0    491
1    348
Name: TP53, dtype: int64
0    622
1    217
Name: ATRX, dtype: int64
0    698
1    141
Name: PTEN, dtype: int64
0    727
1    112
Name: EGFR, dtype: int64
0    728
1    111
Name: CIC, dtype: int64
0    741
1     98
Name: MUC16, dtype: int64
0    766
1     73
Name: PIK3CA, dtype: int64
0    772
1     67
Name: NF1, dtype: int64
0    785
1     54
Name: PIK3R1, dtype: int64
0    794
1     45
Name: FUBP1, dtype: int64
0    799
1     40
Name: RB1, dtype: int64
0    801
1     38
Name: NOTCH1, dtype: int64
0    810
1     29
Name: BCOR, dtype: int64
0    812
1     27
Name: CSMD3, dtype: int64
0    812
1     27
Name: SMARCA4, dtype: int64
0    812
1     27
Name: GRIN2A, dtype: int64
0    816
1     23
Name: IDH2, dtype: int64
0    816
1     23
Name: FAT4, dtype: int64
0    817
1     22
Name: PDGFRA, dtype: int64


In [ ]:
IDH1.value_counts()

0    435
1    404
Name: IDH1, dtype: int64

In [ ]:
IDH1.value_counts()

0    435
1    404
Name: IDH1, dtype: int64

data.head()

In [ ]:
black_africans = data.loc[:, "Race"] == 1
white_women = (data.loc[:, "Gender"] == 1) & (data.loc[:, "Race"] == 0)

In [ ]:
print(len(data[black_africans]))

59


In [ ]:
black_with_glioma = (data.loc[:, "Race"] == 1) & (data.loc[:, "Grade"] == 1)

In [ ]:
len(data[black_with_glioma])

38

In [ ]:
print(38/59)

0.6440677966101694


In [ ]:
white_women_with_glioma = (data.loc[:, "Gender"] == 1) & (data.loc[:, "Race"] == 0) & (data.loc[:, "Grade"] == 1)

In [ ]:
len(data[white_women_with_glioma])

118

In [ ]:
print(118/len(data[white_women]))

0.36990595611285265


In [ ]:
women_only = data[white_women]

In [ ]:
len(women_only.columns)

24

In [ ]:
data.tail()

Grade  Gender  Age_at_diagnosis  Race  IDH1  TP53  ATRX  PTEN  EGFR  CIC  \
834      1       1             77.89     0     0     0     0     1     0    0   
835      1       0             85.18     0     0     1     0     1     0    0   
836      1       1             77.49     0     0     1     0     1     0    0   
837      1       0             63.33     0     0     1     0     0     0    0   
838      1       0             76.61     1     0     0     0     0     0    0   

     ...  FUBP1  RB1  NOTCH1  BCOR  CSMD3  SMARCA4  GRIN2A  IDH2  FAT4  PDGFRA  
834  ...      0    0       0     0      0        0       0     0     0       0  
835  ...      0    0       0     0      0        0       0     0     0       0  
836  ...      0    0       0     0      0        0       0     0     0       0  
837  ...      0    1       0     0      0        0       0     0     0       0  
838  ...      0    0       0     0      0        0       0     0     0       0  

[5 rows x 24 columns]

In [ ]:
women_only.describe().T

count       mean        std    min     25%    50%     75%  \
Grade             319.0   0.369906   0.483537   0.00   0.000   0.00   1.000   
Gender            319.0   1.000000   0.000000   1.00   1.000   1.00   1.000   
Age_at_diagnosis  319.0  50.621975  15.596748  20.32  38.055  50.35  62.265   
Race              319.0   0.000000   0.000000   0.00   0.000   0.00   0.000   
IDH1              319.0   0.526646   0.500074   0.00   0.000   1.00   1.000   
TP53              319.0   0.423197   0.494842   0.00   0.000   0.00   1.000   
ATRX              319.0   0.294671   0.456611   0.00   0.000   0.00   1.000   
PTEN              319.0   0.156740   0.364126   0.00   0.000   0.00   0.000   
EGFR              319.0   0.109718   0.313029   0.00   0.000   0.00   0.000   
CIC               319.0   0.163009   0.369955   0.00   0.000   0.00   0.000   
MUC16             319.0   0.125392   0.331683   0.00   0.000   0.00   0.000   
PIK3CA            319.0   0.078370   0.269175   0.00   0.000   0.00   0.000   
NF1               319.0   0.075235   0.264185   0.00   0.000   0.00   0.000   
PIK3R1            319.0   0.047022   0.212018   0.00   0.000   0.00   0.000   
FUBP1             319.0   0.059561   0.237044   0.00   0.000   0.00   0.000   
RB1               319.0   0.056426   0.231106   0.00   0.000   0.00   0.000   
NOTCH1            319.0   0.047022   0.212018   0.00   0.000   0.00   0.000   
BCOR              319.0   0.050157   0.218611   0.00   0.000   0.00   0.000   
CSMD3             319.0   0.043887   0.205166   0.00   0.000   0.00   0.000   
SMARCA4           319.0   0.034483   0.182752   0.00   0.000   0.00   0.000   
GRIN2A            319.0   0.034483   0.182752   0.00   0.000   0.00   0.000   
IDH2              319.0   0.031348   0.174530   0.00   0.000   0.00   0.000   
FAT4              319.0   0.040752   0.198027   0.00   0.000   0.00   0.000   
PDGFRA            319.0   0.031348   0.174530   0.00   0.000   0.00   0.000   

                    max  
Grade              1.00  
Gender             1.00  
Age_at_diagnosis  85.61  
Race               0.00  
IDH1               1.00  
TP53               1.00  
ATRX               1.00  
PTEN               1.00  
EGFR               1.00  
CIC                1.00  
MUC16              1.00  
PIK3CA             1.00  
NF1                1.00  
PIK3R1             1.00  
FUBP1              1.00  
RB1                1.00  
NOTCH1             1.00  
BCOR               1.00  
CSMD3              1.00  
SMARCA4            1.00  
GRIN2A             1.00  
IDH2               1.00  
FAT4               1.00  
PDGFRA             1.00

In [ ]:
women_only.corr()

Grade  Gender  Age_at_diagnosis  Race      IDH1  \
Grade             1.000000     NaN          0.520570   NaN -0.717147   
Gender                 NaN     NaN               NaN   NaN       NaN   
Age_at_diagnosis  0.520570     NaN          1.000000   NaN -0.510578   
Race                   NaN     NaN               NaN   NaN       NaN   
IDH1             -0.717147     NaN         -0.510578   NaN  1.000000   
TP53             -0.104316     NaN         -0.239888   NaN  0.278338   
ATRX             -0.310083     NaN         -0.398014   NaN  0.419977   
PTEN              0.419803     NaN          0.255413   NaN -0.437483   
EGFR              0.208866     NaN          0.177689   NaN -0.350200   
CIC              -0.302976     NaN         -0.067499   NaN  0.282407   
MUC16             0.141247     NaN          0.103832   NaN -0.115002   
PIK3CA            0.042338     NaN          0.050238   NaN -0.050605   
NF1               0.150712     NaN          0.098362   NaN -0.253252   
PIK3R1            0.136542     NaN          0.109219   NaN -0.086004   
FUBP1            -0.137952     NaN         -0.032405   NaN  0.132475   
RB1               0.234740     NaN          0.019223   NaN -0.257940   
NOTCH1           -0.170197     NaN         -0.030354   NaN  0.180933   
BCOR              0.032174     NaN          0.001050   NaN -0.069794   
CSMD3             0.026034     NaN         -0.049458   NaN -0.011434   
SMARCA4          -0.073626     NaN         -0.110504   NaN  0.041528   
GRIN2A            0.104304     NaN          0.010380   NaN -0.130518   
IDH2             -0.100574     NaN         -0.106720   NaN -0.189752   
FAT4              0.071962     NaN          0.006765   NaN -0.058633   
PDGFRA            0.085739     NaN          0.010559   NaN -0.117692   

                      TP53      ATRX      PTEN      EGFR       CIC  ...  \
Grade            -0.104316 -0.310083  0.419803  0.208866 -0.302976  ...   
Gender                 NaN       NaN       NaN       NaN       NaN  ...   
Age_at_diagnosis -0.239888 -0.398014  0.255413  0.177689 -0.067499  ...   
Race                   NaN       NaN       NaN       NaN       NaN  ...   
IDH1              0.278338  0.419977 -0.437483 -0.350200  0.282407  ...   
TP53              1.000000  0.531917 -0.072600 -0.138290 -0.326478  ...   
ATRX              0.531917  1.000000 -0.184096 -0.138903 -0.173552  ...   
PTEN             -0.072600 -0.184096  1.000000  0.234896 -0.143576  ...   
EGFR             -0.138290 -0.138903  0.234896  1.000000 -0.073462  ...   
CIC              -0.326478 -0.173552 -0.143576 -0.073462  1.000000  ...   
MUC16             0.078019  0.025190  0.175242  0.079090 -0.013336  ...   
PIK3CA            0.009917 -0.009384 -0.029469  0.158878  0.060781  ...   
NF1              -0.003770 -0.054017  0.138548  0.013947  0.034999  ...   
PIK3R1           -0.010430  0.018838  0.026432  0.111549  0.062336  ...   
FUBP1            -0.135137 -0.075503 -0.035633 -0.003587  0.355103  ...   
RB1               0.093009  0.020739  0.342997  0.131497  0.002421  ...   
NOTCH1           -0.100349 -0.013645 -0.055034 -0.030598  0.262793  ...   
BCOR              0.035721  0.008987  0.058947  0.011236  0.170765  ...   
CSMD3             0.095253  0.062926  0.076006  0.218576  0.029742  ...   
SMARCA4           0.116310  0.103957  0.060292  0.098567  0.102646  ...   
GRIN2A            0.011991  0.028588  0.107548  0.263477  0.056135  ...   
IDH2             -0.081269 -0.037357 -0.077559 -0.005594  0.212827  ...   
FAT4              0.080177  0.040665  0.041971  0.130562  0.080735  ...   
PDGFRA            0.027965  0.041563  0.021406  0.109526  0.115421  ...   

                     FUBP1       RB1    NOTCH1      BCOR     CSMD3   SMARCA4  \
Grade            -0.137952  0.234740 -0.170197  0.032174  0.026034 -0.073626   
Gender                 NaN       NaN       NaN       NaN       NaN       NaN   
Age_at_diagnosis -0.032405  0.019223 -0.030354  0.001050 -0.049458 -0.110504   
Race                   N

In [ ]:
data.columns

Index(['Grade', 'Gender', 'Age_at_diagnosis', 'Race', 'IDH1', 'TP53', 'ATRX',
       'PTEN', 'EGFR', 'CIC', 'MUC16', 'PIK3CA', 'NF1', 'PIK3R1', 'FUBP1',
       'RB1', 'NOTCH1', 'BCOR', 'CSMD3', 'SMARCA4', 'GRIN2A', 'IDH2', 'FAT4',
       'PDGFRA'],
      dtype='object')

In [ ]:
X = data.iloc[:, 1:].values
y = data.iloc[:, 0].values

In [ ]:
print(y[0:10])

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 1:2] = sc.fit_transform(X_train[:, 1:2])
X_test[:, 1:2] = sc.transform(X_test[:, 1:2])

In [ ]:
from sklearn.naive_bayes import GaussianNB
bayes = GaussianNB()
bayes.fit(X_train, y_train)

GaussianNB()

In [ ]:
y_pred = bayes.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, y_pred)

In [ ]:
print(acc)

0.7261904761904762


In [ ]:
from sklearn.tree import DecisionTreeClassifier
trees = DecisionTreeClassifier()
trees.fit(X_train, y_train)

DecisionTreeClassifier()

In [ ]:
y_pred_trees = trees.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
acc_trees = accuracy_score(y_test, y_pred_trees)

In [ ]:
print(acc_trees)

0.7797619047619048


In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=20)
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(n_estimators=20)

In [ ]:
y_pred_rf = rf_classifier.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
acc_rf = accuracy_score(y_test, y_pred_rf)

In [ ]:
print(acc_rf)

0.8392857142857143


In [ ]:
from xgboost import XGBClassifier
xg = XGBClassifier()
xg.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [ ]:
y_pred_xg = xg.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
acc_xg = accuracy_score(y_test, y_pred_xg)

In [ ]:
print(acc_xg)

0.8630952380952381


In [ ]:
X.shape

(839, 23)

In [ ]:
inputs = keras.Input(shape=(23,), name="Glioma")
layer_1 = layers.Dense(32, activation="relu", kernel_regularizer=l1(0.001), name="dense_layer_1")(inputs)
#drop_out_layer = layers.Dropout(0.5)(layer_1)
#layer_2 = layers.Dense(16, activation="relu", name="dense_layer_2")(layer_1)
outputs = layers.Dense(2, activation="softmax", name="output_layer")(layer_1)

In [ ]:
model = keras.Model(inputs=inputs, outputs=outputs, name="glioma_model")

In [ ]:
y_pred_ann = model.predict(X_test)
y_pred_ann = (y_pred_ann > 0.5)

6/6 [==============================] - 0s 7ms/step


In [ ]:
model.compile(
    optimizer=keras.optimizers.RMSprop(),
    loss= keras.losses.SparseCategoricalCrossentropy(),
    metrics=[keras.metrics.mae, keras.metrics.sparse_categorical_accuracy]
)

In [ ]:
model.summary()

Model: "glioma_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Glioma (InputLayer)         [(None, 23)]              0         
                                                                 
 dense_layer_1 (Dense)       (None, 32)                768       
                                                                 
 output_layer (Dense)        (None, 2)                 66        
                                                                 
Total params: 834 (3.26 KB)
Trainable params: 834 (3.26 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
print("Fit the model on the training data")
history=model.fit(
    X_train,
    y_train,
    batch_size=16,
    epochs=200,
)

Fit the model on the training data
Epoch 1/200
42/42 [==============================] - 1s 4ms/step - loss: 0.6381 - mean_absolute_error: 0.5000 - sparse_categorical_accuracy: 0.7779
Epoch 2/200
42/42 [==============================] - 0s 3ms/step - loss: 0.5527 - mean_absolute_error: 0.5000 - sparse_categorical_accuracy: 0.8212
Epoch 3/200
42/42 [==============================] - 0s 3ms/step - loss: 0.5123 - mean_absolute_error: 0.5000 - sparse_categorical_accuracy: 0.8256
Epoch 4/200
42/42 [==============================] - 0s 3ms/step - loss: 0.4857 - mean_absolute_error: 0.5000 - sparse_categorical_accuracy: 0.8331
Epoch 5/200
42/42 [==============================] - 0s 3ms/step - loss: 0.4653 - mean_absolute_error: 0.5000 - sparse_categorical_accuracy: 0.8435
Epoch 6/200
42/42 [==============================] - 0s 3ms/step - loss: 0.4499 - mean_absolute_error: 0.5000 - sparse_categorical_accuracy: 0.8480
Epoch 7/200
42/42 [==============================] - 0s 3ms/step - loss: 0.43

In [ ]:
test_scores = model.evaluate(X_test, y_test, verbose=2)
print("Test loss:", test_scores[0])
print("Test accuracy:", test_scores[1])
dict(zip(model.metrics_names, test_scores))

6/6 - 0s - loss: 0.3201 - mean_absolute_error: 0.5000 - sparse_categorical_accuracy: 0.8929 - 274ms/epoch - 46ms/step
Test loss: 0.32013052701950073
Test accuracy: 0.5


{'loss': 0.32013052701950073,
 'mean_absolute_error': 0.5,
 'sparse_categorical_accuracy': 0.8928571343421936}

In [ ]:
# Need to do cross-validation
# need to get other metrics
# write the classification report code tomorrow
# write the predict_poroba code tomorrow

In [ ]:
y_pred_ann[:5]

array([[ True, False],
       [ True, False],
       [False,  True],
       [ True, False],
       [ True, False]])

In [ ]:
predicted_categories = np.argmax(y_pred_ann, axis=1)

In [ ]:
print(predicted_categories[:5])

[0 0 1 0 0]


In [ ]:
print(X_test.shape)

(168, 23)


In [ ]:
true_categories = tf.concat([x,y for x, y in X_test], axis=0).numpy()

SyntaxError: ignored

In [ ]:
true_categories[:10]

array([0.        , 0.23899197, 0.        , 1.        , 0.        ,
       0.        , 0.        , 0.        , 1.        , 0.        ])

In [ ]:
true_categories_argmax = np.argmax(true_categories, axis=1)

AxisError: ignored

In [ ]:
true_categories_argmax

231

In [ ]:
#from sklearn.metrics import classification_report
#target = ["lgg", "gbm"]
#print(classification_report(y_test, y_pred_ann))